[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
#serde = { version = "1.0.219", features = ["derive"] }
#serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
rand = "0.9.0" #测试用。随机生成消息ID

[lib]
name = "network"
path = "src/lib.rs"